# Stage 1: Build
FROM eclipse-temurin:21-jdk AS build
COPY . /project
WORKDIR /project
RUN ./gradlew quarkusBuild -x test

# Stage 2: Runtime
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /project/build/quarkus-app/ ./
EXPOSE 8080
CMD ["java", "-jar", "quarkus-run.jar"]
